### ISSUE TITLE
mkdir for me

### ISSUE THREAD

**Issue by sartak** [genehack/HiD#11]
Seems like HiD could mkdir the destination for me if it doesn't exist, instead of blowing up with this obscure error :)

    Attribute (destination) does not pass the type constraint because: Validation failed for 'HiD_DirPath' with value ../OTHERREPO/NONEXISTENT/ at constructor Tags::new (defined at _plugins/Tags.pm line 7) line 38.
	Tags::new('Tags') called at /Users/sartak/.perl/perls/perl-5.18.1/lib/site_perl/5.18.1/HiD.pm line 342
	HiD::_build_plugins('HiD=HASH(0x7fc73f992d60)') called at reader HiD::plugins (defined at /Users/sartak/.perl/perls/perl-5.18.1/lib/site_perl/5.18.1/HiD.pm line 311) line 7
	HiD::plugins('HiD=HASH(0x7fc73f992d60)') called at /Users/sartak/.perl/perls/perl-5.18.1/lib/site_perl/5.18.1/HiD.pm line 579
	HiD::publish('HiD=HASH(0x7fc73f992d60)') called at /Users/sartak/.perl/perls/perl-5.18.1/lib/site_perl/5.18.1/darwin-2level/Moose/Meta/Method/Delegation.pm line 110
	HiD::App::Command::publish('HiD::App::Command::publish=HASH(0x7fc73fe50178)') called at /Users/sartak/.perl/perls/perl-5.18.1/lib/site_perl/5.18.1/HiD/App/Command/publish.pm line 39

**Comment by genehack** [comment]
I think I finally replicated this and fixed it in 6ff61e52af5521901404b49d1c440b0223a2bd1f so I'm going to close this out...
