### ISSUE TITLE
Make HiD a bit more github pages aware

### ISSUE THREAD

**Issue by sjn** [genehack/HiD#15]
Github offers a hosting solution for open source projects and organizations. They're using Jekyll for templating, and have quite a few assumptions built into their setup.

Can HiD be made a bit more "aware" (DWIMmy) of github conventions, so that it can be used as a tool for managing webages there?

http://pages.github.com/
https://help.github.com/articles/setting-up-a-custom-domain-with-pages

**Comment by genehack** [comment]
@sjn - Just landed preliminary support on this branch. Needs more testing, but it seems to work for me...

**Comment by genehack** [comment]
Merged this to 'master'. 

Command is 'hid publish -G' Add '-v' for extra info on what's happening. 

Will be part of the 2.0 release, along with hopefully a bunch of doc updates and maybe even crazy stuff like blogging templates.

**Comment by genehack** [comment]
This actually went out in v1.92.
