### ISSUE TITLE
Uses File::Slurp, known to be buggy and vulnerable

### ISSUE THREAD

**Issue by karenetheridge** [genehack/HiD#27]
e.g. look at https://rt.cpan.org/Ticket/Display.html?id=83126 and be dismayed

File::Slurp::Tiny and Path::Tiny are both excellent alternatives. See also http://shadow.cat/blog/matt-s-trout/mstpan-5/

**Comment by genehack** [comment]
Please see #26 8^) 

work is in progress, thanks for the poke. Closing.

**Comment by karenetheridge** [comment]
doh, sorry!
