### ISSUE TITLE
PR Challenge March 2016

### ISSUE THREAD

**Issue by lejeunerenard** [genehack/HiD#39]
Hey @genehack,

I was given your module as my march assignment for the [PR Challenge](http://cpan-prc.org/)! I've taken a quick look at the repo and it looks like there is a `TODO` file and lots of issues I could potentially work on. Do you have a preference for what I should work on?

**Comment by genehack** [comment]
Documentation would be the biggest wishlist item, TBH, but I'm not even sure where to suggest you start with that. What are you interested in working on?

**Comment by lejeunerenard** [comment]
@genehack sorry for the grossly late response. I am ok with working on documentation as that will let me get acquainted with the library. I will work on documenting the `hid` command. I figure that's a good place to start since you point people to it in your README but there is nothing there. :)

If you have other ideas, just let me know.

**Comment by genehack** [comment]
No worries at all — if there’s anything I can do to help, please let me know.
