### ISSUE TITLE
add 'hid version'

### ISSUE THREAD

**Issue by genehack** [genehack/HiD#9]
because seriously

**Comment by brianwisti** [comment]
BTW:

~~~
$ hid version
hid (HiD::App) version 1.91 (/Users/brianwisti/perl5/perlbrew/perls/perl-5.20.1/bin/hid)
~~~

Though it's not listed as a command.

~~~
$ hid help
hid <command>

Available commands:

  commands: list the application's commands
      help: display a command's help screen

    config: dump configuration
      init: initialize a new site
   publish: publish site
    server: HiD 'server' subcmd - start up a Plack-based web server for your site
~~~

I assume this is some kind of sorcery.

**Comment by genehack** [comment]
So, it turns out `App::Cmd` injects a `version' command for you (yay!) but hides it from the command list with no way to configure it not too do that (boo!)

Tracking on this issue : https://github.com/rjbs/App-Cmd/issues/45

In the meantime, I will close this out, thanks for pointing out it works.
